### ISSUE TITLE
Custom postgres port is ignored

### ISSUE THREAD

**Issue by jnk-cons** [Unleash/unleash-docker#51]
We try to run the postgres database on a port other than the default 5432. Unfortunately, the unleash container can no longer connect. The environment variable seems to be ignored. Only when using the default port does it work.

Here is the compose file:

```
version: "3.3"

services:
  unleash-db:
    image: postgres:9.6
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_USER: "unleash_user"
      POSTGRES_PASSWORD: "some_password"

  unleash:
    image: unleashorg/unleash-server
    environment:
      DATABASE_HOST: "unleash-db"
      DATABASE_PORT: 5439
      DATABASE_USERNAME: "unleash_user"
      DATABASE_PASSWORD: "some_password"
      DATABASE_NAME: "unleash"
      DATABASE_SSL: "false"
      DATABASE_SCHEMA: "public"
    depends_on:
      - unleash-db
```

**Comment by ivarconr** [comment]
Hi there, 

just changing the ports in the db image will only change what you expose postgres on outside of the the docker-compose setup, Unleash would still need to connect on 5432 with the compose example provided. 

If you really want to change the port postgres is running on you could do something like:

```yaml
version: "3.3"

services:
  unleash-db:
    image: postgres:9.6
    expose:
    - "5439"
    ports:
      - "5439:5439"
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_USER: "unleash_user"
      POSTGRES_PASSWORD: "some_password"
    command: -p 5439

  unleash:
    image: unleashorg/unleash-server
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: "unleash-db"
      DATABASE_PORT: 5439
      DATABASE_USERNAME: "unleash_user"
      DATABASE_PASSWORD: "some_password"
      DATABASE_NAME: "unleash"
      DATABASE_SSL: "false"
      DATABASE_SCHEMA: "public"
    depends_on:
      - unleash-db
```

Whit the above example postgres will be running on port 5439 and unleash will be running on 4242.
